### ISSUE TITLE
doesn't always update meta file

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/git-whosonfirst-data#1]
I expected this commit to also update the meta file, but it didn't.

commit 63919a41e103d3c477f927b07678087fa9f3f850
Author: Nathaniel Kelso nvkelso@gmail.com
Date:   Wed Nov 11 16:19:33 2015 -0800

```
pull Lone Mountain in SF out of the park
```

**Comment by thisisaaronland** [comment]
Was anything printed to STDOUT, like this:

https://github.com/whosonfirst/git-whosonfirst-data#pre-commit

If not then it sounds like the pre-commit hook is not installed correctly.

**Comment by nvkelso** [comment]
Maybe it's only partially installed? I do get something, but not as much as expected:

```
$ git commit -m "update Inner Richmond label position with error for testing" -a
[master 89ae50e] update Inner Richmond label position with error for testing
 2 files changed, 4 insertions(+), 49911 deletions(-)
 rewrite meta/wof-neighbourhood-20151111.csv (99%)
```

and

```
$ git commit -m "update Inner Richmond label position without error (for ever)" -a
[master f822e43] update Inner Richmond label position without error (for ever)
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by thisisaaronland** [comment]
Yeah, you should be seeing something like this:

```
$> git commit -m "add inception date" .
INFO:root:invoking git-whosonfirst-mapzen pre-commit hooks
...
```

**Comment by thisisaaronland** [comment]
It is the case though that neither the changes (lastmodified date, etc.) written to the .geojson file or the meta files are being captured. I need to figure out whether git can git itself without getting stuck in an infinite loop...
